[project]
name = "python-archive"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mpmath>=1.3.0",
    "numpy>=2.2.3",
    "pathfinding>=1.0.16",
    "sympy>=1.13.3",
]
